# Generated by Django 4.2.11 on 2024-06-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0002_candidateprofiles_duplicateprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisibilityToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_user_id', models.IntegerField()),
                ('show_email1', models.BooleanField(default=False)),
                ('show_email2', models.BooleanField(default=False)),
                ('show_phone1', models.BooleanField(default=False)),
                ('show_phone2', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asb.candidateprofiles')),
            ],
        ),
    ]
