# Generated by Django 4.2.11 on 2024-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0003_profilevisibilitytoggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilevisibilitytoggle',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
