# Generated by Django 4.2.11 on 2024-06-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0005_alter_candidateprofiles_company_size_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee_code', models.CharField(max_length=10)),
                ('city_code', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=100)),
                ('department_number', models.CharField(max_length=10)),
                ('region_name', models.CharField(max_length=100)),
                ('region_geojson_name', models.CharField(max_length=100)),
            ],
        ),
    ]
