# Generated by Django 4.2.11 on 2024-07-01 07:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0007_alter_candidateprofiles_person_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
