# Generated by Django 4.2.11 on 2024-07-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0010_alter_savedlistprofiles_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofiles',
            name='company_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='current_company_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='current_position',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='current_position_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='headline',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_industry',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='previous_company_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='previous_company_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='previous_position_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='previous_position_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='company_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='company_size_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='company_size_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='current_company_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='current_position',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='current_position_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='headline',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_industry',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='previous_company_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='previous_company_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='previous_position_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='previous_position_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
