# Generated by Django 4.2.11 on 2024-07-12 10:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0012_alter_candidateprofiles_company_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofiles',
            name='company_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='company_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='company_linkedin_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='company_logo_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='company_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='company_website',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='current_company_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='current_position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='current_position_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_angellist_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_crunchbase_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_facebook_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_image_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_industry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_linkedin_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='person_twitter_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='phone1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='phone2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='previous_company_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='previous_company_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='previous_position_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofiles',
            name='previous_position_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='company_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='company_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='company_linkedin_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='company_logo_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='company_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='company_website',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='current_company_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='current_position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='current_position_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_angellist_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_crunchbase_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_facebook_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_image_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_industry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_linkedin_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='person_twitter_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='phone1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='phone2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='previous_company_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='previous_company_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='previous_position_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicateprofiles',
            name='previous_position_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
