# Generated by Django 4.2.11 on 2024-08-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0013_alter_candidateprofiles_company_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_user_id', models.IntegerField()),
                ('action_user_id', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('action_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asb.candidateprofiles')),
            ],
        ),
    ]
