# Generated by Django 4.2.11 on 2024-08-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0016_alter_actions_action_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_from', models.IntegerField()),
                ('shared_to', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asb.candidateprofiles')),
            ],
        ),
    ]
