# Generated by Django 4.2.11 on 2024-08-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0017_sharedprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedprofiles',
            name='deleted_by_shared_from',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedprofiles',
            name='deleted_by_shared_to',
            field=models.BooleanField(default=False),
        ),
    ]
