# Generated by Django 4.2.11 on 2024-09-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0018_sharedprofiles_deleted_by_shared_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('job_title', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('current_company', models.TextField(blank=True, null=True)),
                ('head_count', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
