# Generated by Django 4.2.11 on 2024-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0019_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
