# Generated by Django 4.2.11 on 2024-10-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0021_need_contact_type_need_percentage_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'phone'), ('email', 'email'), ('phone_or_email', 'phone or email')], max_length=100, null=True),
        ),
    ]
