# Generated by Django 4.2.11 on 2024-10-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0022_alter_need_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='action_type',
            field=models.CharField(choices=[('call', 'call'), ('text_message', 'text messages'), ('voice_email', 'voice email'), ('email', 'email'), ('note', 'note'), ('convert', 'convert'), ('opened_profile', 'opened profile')], max_length=100, null=True),
        ),
    ]
