# Generated by Django 4.2.11 on 2024-11-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0023_alter_actions_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='seniority_levels',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
